import './globals.css'

import { Inter } from 'next/font/google'
import { Providers } from './providers'
import ScrollToTop from '@/components/ScrollToTop'
interface RootLayoutProps {
  children: React.ReactNode
}

export const metadata = {
  title: 'vanlee',
  description: 'My site generated by Next.js'
}

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <>
      <html lang='en' suppressHydrationWarning>
        <head />
        <body className={`bg-[#FCFCFC] dark:bg-black ${inter.className}`}>
          <Providers>
            <ScrollToTop />
          </Providers>
        </body>
      </html>
    </>
  )
}
