import './globals.css'

interface RootLayoutProps {
  children: React.ReactNode
}

export const metadata = {
  title: 'vanlee',
  description: 'My site generated by Next.js'
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <>
      <html>
        <body>{children}</body>
      </html>
    </>
  )
}
