import { Metadata } from 'next'
import Links from './components/nav-links'
// 布局是必须的
export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <Links></Links>

        <main>{children}</main>
      </body>
    </html>
  )
}
